job.go
kubejob_test.go

Use not `$(VALUE)` but `$VALUE` for env values .

Fix handling of env value

---

job.go

Fix kubejob label

---

.github/workflows/test.yaml
Makefile
go.mod
go.sum
job.go

Supports command retries ( max 10 times ) .
Also, added CI with coverage .

Supports command retries

---

codecov.yaml
job.go
kubejob_test.go

Also, add test cases for coverage

Add error handling for (*bytes.Buffer).ReadFrom and Pass new context to cleanup process

---

job.go

Add ExecOnly API

---

job.go

Fix isRunning status

---

job.go

Fix race condition of isRunning property

---

.github/workflows/test.yaml
Makefile
job.go
testdata/config/cluster.yaml
testdata/config/manifest.yaml

Add `(*JobExecutor). ExecPrepareCommand(cmd []string) ([]byte, error)` API.
It support to run command before running main command .
Also, fix CI

Add prepared command for running job

---

job.go
kubejob_test.go

PreInit can define the process you want to execute before the process of init container specified at the time of starting Job.
It is mainly intended to be used when you use `(*JobExecutor).CopyToFile` to copy an arbitrary file to pod before init processing.

Support PreInit step

---

builder.go
copy.go
executor.go
job.go
job_test.go

Also, fix data race error for copy API

Support to hook execution of init container

---

copy.go
executor.go
job.go

Also fix about file permission
- keep permissions when copying files to Pod
- keep permissions for files copied from Pod

Support to retry for copy from Pod

---

error.go
executor.go
job.go

Also, fix error of prepare command .

Support to set timeout for PodInitializing phase

---

executor.go

Do not expand variables in template

Fix command template

---

copy.go

FYI: https://github.com/goccy/kubetest/issues/63

Add retryable error

---

codecov.yaml
job.go

Confirm all container's ready status before move to running status

---

agent.go
agent_client.go
agent_server.go
agent_test.go

Fix copying process for directory

---

README.md
agent.go
agent_test.go
copy.go
executor.go
job.go
job_test.go
preinit.go
util.go

Modify the constructor of AgentConfig to allow settings to be specified on a per-container basis

---

agent.go
agent_client.go
agent_server.go
error.go
executor.go
job.go

The tar file created for copying must be created in a different path or it will fail.

Fix copy process by agent

---

job.go

- If the kubejob runs for more than 4 hours, it will end without an error. However, there is currently no option for a timeout value. Added option to set timeout value.
- https://github.com/goccy/kubejob/issues/40

Added timeout option

---

executor.go

Since force stop may not be possible, this logic is removed.

Remove force stop logic

---

job.go

Sorry my mistake.
Fixed forgetting to pass listOptions to function.

Fixed that watchTimeoutSecond could not be used

---

.github/workflows/test.yaml
agent.go
agent_server.go
agent_test.go
job_test.go

Fix copy process for symlink file
